default_settings: null
behaviors:
  Navigation_Adam:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.005
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 64
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 1000
    max_steps: 15000
    time_horizon: 64
    summary_freq: 1000
    threaded: true
    self_play: null
    behavioral_cloning:
      demo_path: D:\Year4\Project\FKKKKK\SIGGRAPH_2017\12313\Assets\Demos\GailDemo1.demo
      steps: 150000
      strength: 1.0
      samples_per_update: 0
      num_epoch: 3
      batch_size: 512
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: BCTest
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
