behaviors:
  Navigation_Adam:
    trainer_type: ppo

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.005
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encoder_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
      # memory
      memory:
        sequence_length: 64
        memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 15000
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 5
    checkpoint_interval: 1000
    threaded: true
    init_path: null

    #behavior cloning
    behavioral_cloning:
      #demo_path:  D:\Year4\Project\project\SIGGRAPH_2017\Unity\Assets\Demos\45
      #demo_path:  D:\Year4\Project\project\SIGGRAPH_2017\Unity\Assets\Demos\450
      #demo_path:  D:\Year4\Project\project\SIGGRAPH_2017\Unity\Assets\Demos\30
      demo_path:  D:\Year4\Project\project\SIGGRAPH_2017\Unity\Assets\Demos\3450
      steps: 150000
      batch_size: 512
      num_epoch: 3
      samples_per_update: 0
      strength: 0.5

    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1
        gamma: 0.99

      # GAIL
      gail:
        strength: 1.0
        gamma: 0.99
        encoding_size: 128
        #demo_path:  D:\Year4\Project\project\SIGGRAPH_2017\Unity\Assets\Demos\45
        #demo_path:  D:\Year4\Project\project\SIGGRAPH_2017\Unity\Assets\Demos\450
        #demo_path:  D:\Year4\Project\project\SIGGRAPH_2017\Unity\Assets\Demos\30
        demo_path:  D:\Year4\Project\project\SIGGRAPH_2017\Unity\Assets\Demos\3450
        learning_rate: 0.005
        use_actions: false
        use_vail: false

    